### PR TITLE
Support test assembly configuration files

### PR DESCRIPTION
**Pull request by DustinCampbell**

### CODE REVIEW

**Comment by Pilchie** [comment]
:+1:

**Comment by Pilchie** [comment]
Hey @bradwilson Did something change here?  I could swear I looked at this earlier and `TestFrameworkOptions.ForExecution()` used to parse the config itself?

**Comment by bradwilson** [comment]
The empty versions have always just initialized themselves without any values.

**Comment by DustinCampbell** [comment]
We were just using it incorrectly then?

**Comment by Pilchie** [comment]
I think I was confused looking at the console runner, where it will load the config file if it it isn't passed - https://github.com/xunit/xunit/blob/master/src/xunit.runner.utility/Project/XunitProjectAssembly.cs#L25

**Pull request merged**
