### PR TITLE
A few UI tweaks

### PR DESCRIPTION
**Pull request by DustinCampbell**
Notably, the images for passed, failed and skipped have been replaced with images from the Visual Studio Image Library.

### CODE REVIEW

**Comment by DustinCampbell** [comment]
image

**Comment by Pilchie** [comment]
Not pushing back, but why?  What was wrong with the ones I lived from the old Winforms GUI?

**Comment by DustinCampbell** [comment]
'Twas just poking around in the view and decided to make some tweaks. These images don't have the ugly harsh edges that the old icons did. Also, added string formatting so that numbers have digit grouping and bits like that.

I'm looking at this as an opportunity to really refresh that old "ugly" test runner -- make it more functional, improve the workflow, and yes, make it a little more pretty. :smile:

**Comment by Pilchie** [comment]
Note that we should add the currently running testcase to the status bar at some point...

**Comment by Pilchie** [comment]
Filed #29 to track.

**Pull request merged**
